Initial policy code.
kubewarden/share-pid-namespace-policy pull request #3
Opened 2024-01-22 15:01 UTC by jvanz

## Description
Adds the first policy code to validate the `shareProcessNamespace` pod configuration.

Fix https://github.com/kubewarden/kubewarden-controller/issues/598

## Test

```shell
make test e2e-tests
```

2024-01-25 06:20 UTC, fabriziosestito approved these changes

2024-01-25 12:53 UTC, jvanz commented
@kubewarden/kubewarden-developers just in case you've started the review. I've just updated this PR updating the owner name and email address, as well as removing some dependencies from the Cargo file.

2024-01-25 13:53 UTC, flavio requested changes
Overall looks good, I left some minor comments

2024-01-25 16:23 UTC, viccuad commented on .github/workflows/cargo-generate-test.yml
> +name: Try to expand local template using cargo-generate
I think this workflow should be dropped.

2024-01-25 16:25 UTC, viccuad commented on README.md
> +  - apiGroups:
maybe worth to write it in array notation for brevity (like in https://github.com/kubewarden/verify-image-signatures).

2024-01-25 16:32 UTC, viccuad commented on test_data/deployment_with_sharing_pid_namespace_false_admission_request.json
> +      "shareProcessNamespace": false,
since this is a deployment, I think this should be nested under `spec.template.shareProcessNamespace` and not here. Which may change the outcome of E2E tests.

2024-01-25 16:35 UTC, viccuad commented on e2e.bats
> +	run kwctl run  --request-path test_data/deployment_with_sharing_pid_namespace_true_admission_request.json  annotated-policy.wasm
this is consuming a request for a deployment and not a pod, I think this is mean to consume pod_creation.json or similar.

2024-01-25 16:36 UTC, viccuad requested changes
Some mistakes with E2E fixtures mainly.

2024-01-25 17:04 UTC, jvanz commented on .github/workflows/reusable-test-policy-go.yml
> +          sudo cp wasi-gh-action.json /usr/local/lib/tinygo/targets/wasi.json
Ops... I forgot to remove the file after a wrong command to copy files around. Sorry.

2024-01-25 17:16 UTC, jvanz commented on test_data/deployment_with_sharing_pid_namespace_false_admission_request.json
> +      "shareProcessNamespace": false,
Indeed. Thanks for catching that!

2024-01-26 10:01 UTC, viccuad approved these changes

2024-01-29 15:37 UTC, flavio approved these changes
LGTM, ship it

2024-01-29 18:37 UTC, merged